/**
 * This information is generated by running the following snippet on
 * https://developer.algorand.org/docs/get-details/dapps/avm/teal/opcodes/
 *
 * ```js
 * {
 *     const map = (v, fn) => Array.prototype.map.call(v, fn)
 *     const rows = document.querySelector('#asset_holding_get-f ~ div tbody').querySelectorAll('tr')
 *     const object =
 *         map(rows, v => v.querySelectorAll('td'))
 *         .map(v => map(v, v => v.innerText))
 *         .map(([index, name, type, _in, notes]) => ({index: parseInt(index), name, type, in: _in, notes}))
 *         .reduce((acc, v) => (acc[v.name] = v, acc), {})
 *     const text =
 *         JSON.stringify(object, null, 2)
 *         .replaceAll(/"([^"]+)":/g, "$1:")
 *         .replaceAll(/ *in: "", *\n/g, '')
 *         .replaceAll(/'/g, '\\\'')
 *         .replaceAll(/"/g, '\'')
 *     console.log(text)
 * }
 * ```
 */
export default {
  AssetBalance: {
    index: 0,
    name: 'AssetBalance',
    type: 'uint64',
    in: 'Amount of the asset unit held by this account'
  },
  AssetFrozen: {
    index: 1,
    name: 'AssetFrozen',
    type: 'uint64',
    in: 'Is the asset frozen or not'
  }
} as const
